language: python
cache: pip

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt

# Rerun the tests out of the container to get coverage data
script: nosetests smartsearch.tests